config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :items, :books
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true, length: { minimum: 5 }
  validates :year, presence: true, length: { is: 4 }, numericality: { only_integer: true }
  validates :genre, presence: true
  validates :format, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :owned_since, presence: true
  validates :location, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render 'new'
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path
    else
      render 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :year, :genre, :owned_since, :format, :read, :notes)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to items_path
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to items_path
  end
  
  private
  def item_params
    params.require(:item).permit(:title, :owned_since, :info, :broken, :location)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
      <%= pluralize(@book.errors.count, "error") %> occured:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.input :title %>
    <%= f.input :author %>
    <%= f.input :year, label: "Year Published" %>
    <%= f.input :genre, as: :radio_buttons, collection: [["fiction", "fiction"], ["nonfiction", "non-fiction"]], label_method: :second, value_method: :first %>
    <%= f.input :owned_since, start_year: 1990, end_year: Date.today.year, order: [:month, :day, :year] %>
    <%= f.input :format, label: "Format:", as: :radio_buttons, collection: [["fiction", "paperback"], ["hardcover", "hardcover"], ["pdf", "PDF"], ["epubmobi", "EPUB/MOBI"]], label_method: :second, value_method: :first %>
    <%= f.input :read %>
    <%= f.input :notes %>
    <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<%= link_to 'Back', books_path, class: "button primary pull-right" %>
<%= render 'form' %>

app/views/books/index.html.erb
<%= link_to "+", new_book_path, class: "pull-right button primary" %>
<h1>books</h1>
<table class="striped">
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Year published</th>
    <th>Genre</th>
    <th>Format</th>
    <th>Read?</th>
    <th>Notes</th>
    <th>Edit</th>
  </tr>

  <% @books.each do |book| %>
    <tr>
      <td><%= link_to book.title, book_path(book) %></td>
      <td><%= book.author %></td>
      <td><%= book.year %></td>
      <td><%= book.genre == "fiction" ? "fiction" : "non-fiction" %>
      <td><%= book.format %></td>
      <td><%= book.read ? "yes" : "no" %></td>
      <td><%= book.notes %></td>
      <td><%= link_to 'edit', edit_book_path(book) %> <%= link_to 'delete', book_path(book), method: :delete, data: { confirm: "Are you sure you want to delete this item?" } %></td>
    </tr>
  <% end %>
</table>

app/views/books/new.html.erb
<%= link_to 'Back', books_path, class: "button primary pull-right" %>
<h1>add new book</h1>
<%= render 'form' %>

app/views/books/show.html.erb
<h2><%= @book.title %></h2>
<h3>by <%= @book.author %></h3>
<%= link_to 'Back', books_path %>

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>
      <%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :title, label: "Item name" %>
  <%= f.input :owned_since, start_year: 1990, end_year: Date.today.year, order: [:month, :day, :year] %>
  <%= f.input :broken, label: "This item is broken" %>
  <%= f.input :info, label: "Additional info" %>
  <%= f.input :location, label: "Item location: ", as: :radio_buttons, collection: [[1, 'Home'], [2, 'My brother'], [3,'My mother']], label_method: :second, value_method: :first %>
  <%= f.submit %>

<% end %>

app/views/items/edit.html.erb
<%= link_to 'Back', items_path, class: "button primary pull-right" %>
<h1>edit item</h1>
<%= render 'form' %>

app/views/items/index.html.erb
<%= link_to "+", new_item_path, class: "pull-right button primary" %>
<h1>items</h1>
<table class="striped">
  <tr>
    <th>Title</th>
    <th>Owned since</th>
    <th>Broken?</th>
    <th>Location</th>
    <th>Info</th>
    <th>Edit</th>
  </tr>
  <% @items.each do |item| %>
    <tr>
      <td><%= link_to item.title, item_path(item) %></td>
      <td><%= item.owned_since %></td>
      <td><%= item.broken ? "yes" : "no" %></td>
      <td><%= item.location %></td>
      <td><%= item.info %></td>
      <td><%= link_to 'edit', edit_item_path(item)%> <%= link_to 'delete', item_path(item), method: :delete, data: { confirm: 'Are you sure you want to delete this item?' } %></td>
    </tr>
  <% end %>

</table>

app/views/items/new.html.erb
<%= link_to 'Back', items_path, class: "button primary pull-right" %>
<h1>add new item</h1>
<%= render 'form' %>

app/views/items/show.html.erb
<h1>view item</h1>
<p>
  <strong><%= @item.title %></strong>
</p>
<p>
  Owned since: <%= @item.owned_since %>
</p>
<p>
  Broken: <%= @item.broken %>
</p>
<p>
  Location: <%= @item.location %>
</p>
<p>
  Info: <%= @item.info %>
</p>
<p>
  Date added: <%= @item.created_at %>
</p>
<p>
  Last modified: <%= @item.updated_at %>
</p>
<%= link_to 'Back', items_path, class: "button primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="content">
      <%= render "shared/nav" %>
      <div class="main">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <p>This is a footer</p>
</div>

app/views/shared/_nav.html.erb
<nav class="nav">
  <div class="nav-left">
    <%= link_to "items", items_path %>
    <%= link_to "books", books_path %>
  </div>
  <div class="nav-center">
    <%= link_to "inventory", { controller: "welcome" }, class: "brand" %>
  </div>
  <div class="nav-right">
    <a href="#">about</a>
  </div>
</nav>
<hr>

app/views/welcome/index.html.erb
<h1>Personal inventory</h1>
<%= link_to 'Items', controller: 'items' %>
<%= link_to 'New item', new_item_path %>
<hr>
<%= link_to 'Books', controller: 'books' %>
<%= link_to 'New book', new_book_path %>